server:
   port: 8888

spring:
   http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      
   session:
      store-type: redis
      
   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      # password: 没有密码就不要写
      timeout: 5000
      jedis:
         pool:
            max-active: 8
            max-wait: 8000



